In [2]:
import numpy as np
import pandas as pd

In [3]:
corps_cc_df = pd.read_csv('Corporations/Corporations Responses/Climate Change/2018_Full_Climate_Change_Dataset.csv')
na_hq_df = pd.read_csv('Supplementary Data/Locations of Corporations/NA_HQ_public_data.csv')
corps_cc_info = pd.read_csv('Corporations/Corporations Disclosing/Climate Change/2018_Corporates_Disclosing_to_CDP_Climate_Change.csv')

In [4]:
# variables to be defined
survey_year = 2018
survey_type = 'Climate Change'

In [5]:
corps_cc_df.head()

,account_number,organization,survey_year,response_received_date,accounting_period_to,ors_response_id,submission_date,page_name,module_name,question_number,question_unique_reference,column_number,column_name,table_columns_unique_reference,row_number,row_name,data_point_name,data_point_id,response_value,comments
0,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,State the start and end date of the year for w...,3.0,C0.2_C3Indicate if you are providing emissions...,C0.2_c3-Indicate if you are providing emission...,1,Row 1,C0.2_C3_State the start and end date of the ye...,8476,No,NaN
1,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.4,C0. Introduction,C0.4,Select the currency used for all financial inf...,NaN,C0.4,C0.4,0,NaN,C0.4Select the currency used for all financial...,1252,USD,NaN
2,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,State the start and end date of the year for w...,2.0,C0.2_C2End date,C0.2_c2-End date,1,Row 1,C0.2_C2_State the start and end date of the ye...,7523,2017-12-31,NaN
3,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.3,C0. Introduction,C0.3,Select the countries/regions for which you wil...,NaN,C0.3,C0.3,0,NaN,C0.3Select the countries/regions for which you...,1251,Argentina; Barbados; Belize; Bolivia (Plurinat...,NaN
4,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.5,C0. Introduction,C0.5,Select the option that describes the reporting...,NaN,C0.5,C0.5,0,NaN,C0.5Select the option that describes the repor...,163,Operational control,NaN

In [6]:
# adding headquarter location data
hq_data = na_hq_df[(na_hq_df['survey_year'] == survey_year) & (na_hq_df['theme'] == survey_type)]
hq_data = hq_data[['account_number','hq_country','address_city','address_state','address_lat','adress_long']]
hq_data = hq_data.rename(columns={'address_city':'hq_city','address_state':'hq_state','address_lat':'hq_lat','adress_long':'hq_long'})

corps_cc_cities = pd.merge(corps_cc_df, hq_data, how='left', on='account_number')

In [7]:
corps_cc_cities.organization.unique()

array(['Archer Daniels Midland', 'Pfizer Inc.', 'Berry Global Group, Inc',
       'SNC-Lavalin Group Inc.', 'Canadian Tire Corporation, Limited',
       'Canadian Imperial Bank of Commerce (CIBC)',
       'Loblaw Companies Limited', 'Metro Inc.',
       'Wheaton Precious Metals', 'Power Corporation of Canada',
       'CAE Inc.', 'Finning International Inc.', 'IGM Financial Inc.',
       'First Capital Realty Inc.', 'Inter Pipeline Ltd.',
       'Intact Financial Corporation', 'TransAlta Corporation',
       'Tourmaline Oil Corp', 'ARC Resources Ltd.', 'AltaGas Ltd.',
       'Crescent Point Energy Corporation', 'Husky Energy Inc.',
       'Vermilion Energy Inc.', 'Keyera Corp.', 'TC Energy',
       'Enerplus Corporation', 'Enbridge Inc.', 'Teck Resources Limited',
       'Canadian Natural Resources Limited', 'Goldcorp Inc.',
       'Agnico-Eagle Mines Limited', 'Power Financial Corporation',
       'Seven Generations Energy', 'National Bank of Canada',
       'Franco-Nevada Corporation', 'Great-West Lifeco Inc.',
       'Bank of Nova Scotia (Scotiabank)', 'Bank of Montreal',
       'Royal Bank of Canada', 'TD Bank Group',
       'Industrial Alliance Insurance and Financial Services Inc.',
       'Eldorado Gold Corporation', 'MEG Energy Corp.',
       'Baytex Energy Corp.', 'Biogen Inc.', 'AbbVie Inc',
       'Becton, Dickinson and Co.', 'Agilent Technologies Inc.',
       'Trans-Expedite Inc.', 'Microsoft Corporation',
       'International Business Machines (IBM)',
       'Kinross Gold Corporation', 'ShawCor Ltd.', 'Stantec Inc.',
       'Cogeco Inc.', 'Laurentian Bank of Canada', 'Quebecor Inc.',
       'Transcontinental Inc.', 'Centerra Gold Inc.',
       'HudBay Minerals Inc.', 'Capital Power Corporation',
       'Resolute Forest Products Inc.', 'Bonavista Energy Corporation',
       'Algonquin Power & Utilities Corporation',
       'Allseating Corporation', 'Desjardins Group', 'Keilhauer',
       'Stance Healthcare', 'Canadian National Railway Company',
       'Canadian Pacific Railway', 'Catalyst Paper Corporation',
       'Gildan Activewear Inc.', 'Inscape Corporation',
       'Suncor Energy Inc.', 'Stella-Jones Inc', 'Saputo Inc.',
       'Emera Inc.', 'Rogers Communications Inc.', 'Aimia Inc.',
       'Maple Leaf Foods Inc.', 'Dell Technologies', 'Oracle Corporation',
       'Symantec Corporation', 'JLL', 'Verizon Communications Inc.',
       'Xerox Corporation', 'Salesforce.com, Inc.', 'Ivanhoe Mines',
       'Parex Resources Inc', 'Alphabet, Inc.', 'Hilton Worldwide, Inc.',
       'Marriott International, Inc.', 'Bank of America',
       'American Airlines Group Inc', 'Automatic Data Processing, Inc.',
       'Cisco Systems, Inc.', 'Hewlett Packard Enterprise Company',
       'BGIS', 'TTR Transport', 'NetApp Inc.', 'Teradata Corp.',
       'American Express', 'Iron Mountain Inc.', 'HP Inc', 'Lenovo Group',
       'CA Technologies', 'ManpowerGroup', 'Ernst & Young LLP (USA)',
       'Steelcase', 'Omnicom Group Inc.', 'United Airlines Holdings',
       'Broadridge Financial Solutions Inc', 'EQUINIX, INC.',
       'Marsh & McLennan Companies, Inc.', 'Delta Air Lines',
       'Hertz Global Holdings', 'Hyatt Hotels', 'The Southern Company',
       'Varex Imaging Corporation', 'Dominion Energy',
       'Regions Financial Corporation', 'Northwest Seaport Alliance',
       'Guess ?, Inc.', 'Port of Tacoma', 'Vulcan Materials Company',
       'Packaging Corporation Of America', 'Southwest Airlines Co.',
       'Intel Corporation', 'Micron Technology, Inc.',
       'NVIDIA Corporation', 'Western Digital Corp', 'Pitney Bowes Inc.',
       'THE PEER GROUP INC.', 'Van Amerongen & Sons INC',
       'Akamai Technologies Inc', 'Adobe, Inc.',
       'Level 3 Communications, Inc.', 'VMware, Inc',
       'Deloitte Touche Tohmatsu Limited', 'CenturyLink',
       'General Motors Company', 'MetLife, Inc.', 'Wells Fargo & Company',
       'ENGIE Impact', 'PG&E Corporation', 'Duke Energy Corporation',
       'Juniper Networks, Inc.', 'Flex Ltd.', 'Arista Networks',
       'Texas Instruments Incorporated', 'Analog Devices, Inc.',
       'ON Semiconductor', 'SL Green Realty Corp.',
       'Essential Utilities, Inc', 'Digital Realty Trust Inc',
       'CONSOL Energy Inc', 'Marvell Technology Group, Ltd.',
       'Microchip Technology', 'Integrated Device Technology, Inc.',
       'Graphic Packaging International LLC', 'Eaton Corporation',
       'Virtusa', 'WestRock Company', 'Unum Group', 'Alcoa Corp.',
       'The Dow Chemical Company', 'Ecolab Inc.', 'Tyson Foods, Inc.',
       'Kimberly-Clark Corporation', 'Mondelez International Inc',
       'DuPont de Nemours, Inc.', 'Air Products & Chemicals, Inc.',
       'Linde PLC', 'Celanese Corporation', 'Eastman Chemical Company',
       'General Electric Company', 'W.W. Grainger, Inc.',
       'Interpublic Group of Companies, Inc.', 'Exelon Corporation',
       'Textron Inc.', '3M Company', 'CommScope, Inc.',
       'Ford Motor Company', 'Corning Incorporated', 'Apple Inc.',
       'Waste Management, Inc.', 'Xcel Energy Inc.',
       'The AES Corporation', 'Royal Caribbean Cruises Ltd',
       'Cummins Inc.', 'Citigroup Inc.', 'JPMorgan Chase & Co.',
       'Ryder System, Inc.', 'DTE Energy Company', 'Ameren Corporation',
       'VF Corporation', 'CVS Health', 'Sempra Energy',
       'Goldman Sachs Group Inc.',
       'American Electric Power Company, Inc.', 'Autodesk, Inc.',
       'UnitedHealth Group Inc', 'WEC Energy Group',
       'Honeywell International Inc.', 'Parker-Hannifin Corporation',
       'Exela Technologies', 'Kimball Electronics',
       'West Pharmaceutical Services', 'Jetblue Airways Corporation',
       'Boeing Company', 'Lexmark International, Inc.', 'BNY Mellon',
       'Fiserv, Inc.', 'Visa', 'American Sugar Refining, Inc.',
       'Tessy Plastics', 'Hp Hood Llc',
       'Sungard Availability Services (Sungard AS)',
       'ROBIN ENTERPRISES CO', 'Domtar Corporation',
       'Alliance Data Systems', 'Amtrak', "Moody's Corporation",
       'Thomson Reuters Corporation', 'S&P Global',
       'Mastercard Incorporated', 'PPG Industries, Inc.', 'BorgWarner',
       'Avaya', 'Alliance One International Inc.', 'Ciena Corp.',
       'ADTRAN INC', 'SHI International Corp.',
       'WORLD WIDE TECHNOLOGY HOLDING COMPANY', 'Ingram Micro Inc.',
       'MILLENNIUM TECHNICAL SERVICES', 'PS ENERGY GROUP INC',
       'Microsemi Corporation', 'Central Business Forms, Inc',
       'AVIOTRADE INC', 'DG3 NORTH AMERICA INC',
       'Goodyear Tire & Rubber Company', 'Tenneco', 'Cabot Corporation',
       'Sherwin-Williams Company', 'Birla Carbon', 'Novelis Inc.',
       'BECK GROUP - HC BECK', 'SONIM TECHNOLOGIES INC',
       'CALIENTE CONSTRUCTION INC', 'Sykes Enterprises Incorporated',
       'ABM INDUSTRIES INC', 'Fourstar Connections, Inc.',
       'CORPORATE CARE', 'POTTERS CONSTRUCTION',
       'Clune Construction Company', 'MENEMSHA COMPANIES',
       'Brady Corporation', 'PCTEL', 'VIVOTEK LTD', 'Gates Corporation',
       'HARVEST LAND CO-OP, INC.', 'Trillium Health Care',
       'Satellite Logistics Group', 'GENESYS EUROPE LTD (Global)',
       'GROUP O, INC', 'Syniverse', 'Netgear', 'Hamilton Safe Company',
       'Bloomberg', 'Harvard Maintenance, Inc.',
       'Cooper Standard Automotive', 'Trinseo LLC',
       'Baxter International Inc.', 'AmerisourceBergen Corp.',
       'Public Service Enterprise Group Inc.', 'Waters Corporation',
       'Rockwell Automation', 'PerkinElmer, Inc.', 'Chubb Limited',
       'Unisys Corporation', 'Hormel Foods', 'Sysco Corporation',
       'Simon Property Group',
       'The Hartford Financial Services Group, Inc.', 'Tapestry Inc',
       'Smithfield Foods, Inc.', "Macy's, Inc.",
       'Illinois Tool Works Inc.', 'K&A Machine & Tool, Inc.',
       'Modern Machine & Metal Fabricators, Inc.',
       'Zatkoff Seals and Packing', 'M&M Cartage', 'SERIGRAPH, INC.',
       'ULTRA TOOL & MANUFACTURING, INC.',
       'Charles River Laboratories International Inc.',
       'Fujimi Incorporated', 'Rinchem Company Inc', 'Labbeemint',
       'GW Plastics', 'Cartus', 'Norwood Medical',
       'APPLIED ACOUSTICS INTERNATIONAL', 'Healthy Food Ingredients',
       'CAMPBELL WRAPPER CORP', 'MILAN EXPRESS CO INC',
       'The Kraft Heinz Company', 'PepsiCo, Inc.',
       'Starbucks Corporation', 'Cigna', 'Emerson Electric Co.', 'Cavium',
       'EMO TRANS', 'SMART Modular Technologies',
       'ARTESYN EMBEDDED TECHNOLOGIES', 'LATTICE SEMICONDUCTOR', 'NDK',
       'SEMTECH', 'LUMENTUM', 'NEOPHOTONICS CORPORATION',
       'Roskam Baking Company/Rothbury Farms', 'Sensory Effects',
       'Bright International Corp.', 'ANISA INTERNATIONAL INC',
       'KOBO PRODUCTS', 'BELLIS STEEL COMPANY, INC.',
       'CONTROLPOINT TECHNOLOGIES', 'F & G CONSTRUCTION', 'Owens Corning',
       'Tenet Healthcare Corporation', 'Motorola Solutions',
       'Kellogg Company', 'Stanley Black & Decker, Inc.',
       'Republic Services, Inc.', 'L3Harris Technologies INC',
       'Merck & Co., Inc.', 'Raytheon Company', 'Anthem Inc',
       'Navistar International Corporation', 'Carnival Corporation',
       'Host Hotels & Resorts, Inc.', 'Healthpeak Properties, Inc.',
       'Altria Group, Inc.', "McDonald's Corporation", 'Kroger',
       'Bizlink', 'REGAL BELOIT', 'Neapco', 'KC Transportation',
       'PRECISION PIPELINE SOLUTIONS', 'NEW ENGLAND UTILITY CONSTRUCTORS',
       'OMARK Consultants, Inc.', 'Hartford Paving', 'COX INDUSTRIES',
       'CHA HOLDINGS', 'NORTHLINE UTILITIES', 'WS Hampshire, Inc.',
       'LOUREIRO ENGINEERING ASSOCIATES, INC.',
       'MILLENNIUM REAL ESTATE SERVICE', 'TSM CORP', 'Edelman',
       'Tosoh Quartz', 'Tosoh SMD', 'Moses Lake Industries',
       'CABOT MICROELECTRONICS CORP', 'Versum', 'Kelly Services',
       'Turtle & Hughes', 'Brewer Science',
       'Water Technologies & Solutions', 'Entegris Inc',
       'Kmg Electronic Materials', 'Form Factor Inc.', 'Comar, Inc.',
       'Silgan Plastics', 'KIK Custom Products',
       'Philip Morris International', 'Target Corporation', 'News Corp',
       'Avon Products, Inc.', 'Genworth Financial, Inc.',
       'Voya Financial', 'Lennox International Inc', 'Legg Mason, Inc.',
       'Sealed Air Corp.', 'Las Vegas Sands Corporation',
       'Zimmer Biomet Holdings, Inc.', 'The Mosaic Company',
       'The Home Depot, Inc.', 'OGE Energy Corp.', 'NRG Energy Inc',
       'Pinnacle West Capital Corporation', 'NiSource Inc.',
       'FirstEnergy Corporation', 'Halliburton Company',
       'Anadarko Petroleum Corporation', 'EOG Resources, Inc.',
       'Devon Energy Corporation', 'Freeport-McMoRan Inc.', 'Oneok Inc.',
       'PACCAR Inc', 'Kansas City Southern', 'Deere & Company',
       'Newmont Mining Corporation', 'Aetna Inc.', 'eBay Inc.',
       'Edwards Lifesciences Corp', 'T Mobile USA inc',
       'Charles Schwab Corporation', 'AFLAC Incorporated',
       'Capital One Financial', 'Estee Lauder Companies Inc.',
       'Prudential Financial, Inc.', 'Stryker Corporation',
       'Yum! Brands, Inc.', 'The Allstate Corporation', 'NIKE Inc.',
       'Prologis', 'Regeneron Pharmaceuticals, Inc.',
       "Lowe's Companies, Inc.", 'PPL Corporation', 'CRC INDUSTRIES INC',
       'Crown Prince', 'Cousin Corporation of America',
       'Mario Camacho Foods, Llc', 'FORGE INDUSTRIES INC',
       'Star of the West', 'American Packaging', 'NORTHERN CLEARING',
       'GZA Geoenvironmental, Inc.', 'DAVEY TREE EXPERT',
       'The Travelers Companies, Inc.', 'Bristol-Myers Squibb',
       'TJX Companies, Inc.', 'PNC Financial Services Group, Inc.',
       'Amgen, Inc.', 'Franklin Resources, Inc.', 'Fifth Third Bancorp',
       'Costco Wholesale Corporation', 'AvalonBay Communities',
       'Ameriprise Financial, Inc.', 'Welltower Inc.',
       'T. Rowe Price Associates, Inc.', 'Dover Corporation',
       'Dentsply Sirona Inc.', 'L Brands, Inc.',
       'Principal Financial Group, Inc.', 'CBS Corp.',
       'Huntington Bancshares Incorporated',
       'Laboratory Corporation of America Holdings',
       'Citizens Financial Group Inc', 'Ventas Inc', 'KeyCorp',
       'Best Buy Co., Inc.', 'MGM Resorts International',
       'Comerica Incorporated', 'Lincoln National Corporation',
       'Verisk Analytics Inc', 'Henry Schein Inc.', "Kohl's Corporation",
       'H&R Block Inc', 'Affiliated Managers Group', 'Nordstrom, Inc.',
       'Kimco Realty', 'Cincinnati Financial Corporation',
       'Wyndham Destinations, Inc.', 'Tiffany & Co.', 'Hologic, Inc.',
       'Gap Inc.', 'Macerich Co.', 'Baker Hughes Company',
       'Covanta Energy Corporation', 'Viacom Inc.',
       'Caesars Entertainment', 'Varian Medical Systems Inc', 'jcpenney',
       'Vectren Corporation', 'Idacorp Inc', 'Multipet International',
       'Harris Tea Company', 'Tower Labs', 'INDULGENT FOODS',
       'Genfoot America Inc', 'Chroma', 'Shason Inc.',
       'Keysight Technologies Inc', 'MEDELA INC', 'Del Monte Foods',
       'Pacific World Corporation', 'California Resources Corp',
       'Schnitzer Steel Industries, Inc.', 'UNFI',
       'National Office Furniture', 'Ormat Technologies Inc',
       'Wisconsin Energy Conservation Corporation (WECC)',
       'HNI Corporation', 'Teradyne Inc.', 'OFS Brands',
       'Albertsons Companies, Inc.', 'World Bank Group',
       'Actiontec Electronics', 'Davies Office Refurbishing, Inc.',
       'Forest City Realty Trust', 'Krueger International, Inc',
       'Compatico', "Dunkin' Brands Group", 'Terex Corporation',
       'Kimball International, Inc.', 'Abercrombie & Fitch Co.',
       'First Solar Inc', 'ModusLink Corporation',
       'Cypress Semiconductor Corporation', 'QUALCOMM Inc.', 'Dana',
       'Xilinx Inc', 'Booz Allen Hamilton', 'EMCOR Group Inc.',
       'American Cleaning Supply, Inc.', 'All Access Apparel, Inc.',
       'Epic Designers', 'American Textile Company, Inc.',
       'Garan Manufacturing Corp', 'Yotrio Group', 'Norcom, Inc.',
       'Pacific Market International', 'Milestone AV Technologies',
       'Norpac Foods, Inc.', 'Perfection Bakeries Inc.',
       'Town & Country Linen', 'Trimble Navigation Ltd.',
       'Walgreens Boots Alliance', 'Ashland Global Holdings Inc',
       'FMC Corp', 'E.I. du Pont de Nemours and Company',
       'Occidental Petroleum Corporation', 'Procter & Gamble Company',
       'Greif Inc', 'Colgate Palmolive Company', 'Johnson & Johnson',
       'Celgene Corporation', 'Interface, Inc.', 'Bumble Bee Foods LLC',
       'Tennant Company', 'J M HUBER', 'AMKOR TECHNOLOGY INC',
       'Steris plc', 'Agropur Cooperative', 'Abbott Laboratories',
       'Cardinal Health Inc.', 'Allergan plc', 'Assurant, Inc.',
       'Twenty-First Century Fox', 'Comcast Corporation',
       'McCormick & Company, Incorporated', 'U.S. Bancorp',
       'AK Steel Holding Corporation', 'Axalta Coating Systems',
       'Visteon', 'CSX Corporation', 'Union Pacific Corporation',
       'Avery Dennison Corporation', 'Arconic Corp',
       'Norfolk Southern Corp.', 'CMS Energy Corporation', 'Mars',
       'Walt Disney Company', 'The Coca-Cola Company',
       'General Mills Inc.', 'Conagra Brands Inc',
       'Campbell Soup Company', 'Church & Dwight Co., Inc',
       'Clorox Company', 'Hanesbrands Inc.', 'H.B. Fuller',
       'Applied Materials Inc.', 'Lam Research Corp.', 'KLA',
       'AptarGroup', 'Herman Miller', 'Wesco International',
       'American International Group, Inc. (AIG)',
       'Quest Diagnostics Incorporated',
       'Compass Minerals International Inc', 'Morgan Stanley',
       'Express Scripts Holding Company', 'State Street Corporation',
       'BlackRock', 'Eversource Energy', 'Xylem Inc', 'Leidos',
       'United Technologies Corporation', 'Walmart, Inc.',
       'ConocoPhillips', 'Avangrid Inc', 'Fluor Corporation', 'CREE INC.',
       'Rockline Industries', 'Hasbro, Inc.', 'Levi Strauss & Co.',
       'The J.M. Smucker Company', 'Pinnacle Foods Group',
       'Keurig Green Mountain', 'Molson Coors Brewing Company',
       'Hess Corporation', 'Northrop Grumman Corp', 'Humana Inc.',
       'Lockheed Martin Corporation', 'Worldpay Inc',
       'American Water Works', 'Keurig Dr Pepper',
       'Brown-Forman Corporation', 'Constellation Brands, Inc.',
       'Eli Lilly & Co.', 'Masco Corporation', 'Farmer Brothers',
       'Intuit Inc.', 'PVH Corp', 'DW Morgan, LLC', 'Bel Fuse Inc.',
       'Bernhardt Design a Division of Bernhardt Furniture Company',
       'Johnson Controls International PLC',
       'LyondellBasell Industries N.V.', 'UPS', 'Kohler Co.',
       'Radio Flyer Inc', 'CBRE Group, Inc.', 'AT&T Inc.',
       'FedEx Corporation', 'Expeditors International of Washington',
       'Cargill', 'Crown Holdings',
       'International Flavors & Fragrances Inc.',
       'International Paper Company', 'Bemis Company', 'Ball Corporation',
       'Bunge', 'CCL Industries', 'Telus Corporation', 'Air Canada',
       'Avantor', 'Jabil Inc.', 'Ingredion Incorporated',
       'Manulife Financial Corp.', 'Sun Life Financial Inc.',
       'Celestica Inc.', 'BCE Inc.', 'BlackBerry Limited', 'WSP',
       'Magna International Inc.', 'BRP'], dtype=object)

In [8]:
# adding industry data
corps_cc_info = corps_cc_info[['account_number','activities','sectors','industries','primary_activity','primary_sector','primary_industry','primary_questionnaire_sector']]

corps_cc_full = pd.merge(corps_cc_cities, corps_cc_info, how='left', on='account_number')

In [9]:
corps_cc_full.head()

,account_number,organization,survey_year,response_received_date,accounting_period_to,ors_response_id,submission_date,page_name,module_name,question_number,...,hq_state,hq_lat,hq_long,activities,sectors,industries,primary_activity,primary_sector,primary_industry,primary_questionnaire_sector
0,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,...,IL,NaN,NaN,"Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco"
1,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.4,C0. Introduction,C0.4,...,IL,NaN,NaN,"Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco"
2,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,...,IL,NaN,NaN,"Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco"
3,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.3,C0. Introduction,C0.3,...,IL,NaN,NaN,"Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco"
4,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.5,C0. Introduction,C0.5,...,IL,NaN,NaN,"Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco"

### Introduction

In [15]:
# (C0.3) Select the countries/regions for which you will be supplying data.

corps_cc_df[(corps_cc_df['question_number'] == 'C0.3')][['organization','response_value']].set_index(['organization']).apply(lambda x: x.str.split(';').explode()).reset_index()

                organization                     response_value
0     Archer Daniels Midland                          Argentina
1     Archer Daniels Midland                           Barbados
2     Archer Daniels Midland                             Belize
3     Archer Daniels Midland   Bolivia (Plurinational State of)
4     Archer Daniels Midland                             Brazil
...                      ...                                ...
7064                     BRP                            Austria
7065                     BRP                             Canada
7066                     BRP                            Finland
7067                     BRP                             Mexico
7068                     BRP           United States of America

[7069 rows x 2 columns]

<span style="color:red">Splitting out company with each country they responded with</span>

In [34]:
# (C1.1) Is there board-level oversight of climate-related issues within your organization?

corps_cc_df[(corps_cc_df['question_number'] == 'C1.1')]

Empty DataFrame
Columns: [account_number, organization, survey_year, response_received_date, accounting_period_to, ors_response_id, submission_date, page_name, module_name, question_number, question_unique_reference, column_number, column_name, table_columns_unique_reference, row_number, row_name, data_point_name, data_point_id, response_value, comments]
Index: []

<span style="color:red">No one responded to this question???</span>

### Risks and Opportunities

In [41]:
#(C2.3a) Provide details of risks identified with the potential to have a substantive financial or strategic impact on your business.

corps_cc_df_2_3a = corps_cc_df[corps_cc_df['question_number'] == 'C2.3a']
corps_cc_df_2_3a = corps_cc_df_2_3a[corps_cc_df_2_3a['response_value'].notnull()]

corps_cc_df_2_3a = corps_cc_df_2_3a.pivot_table(index=['account_number', 'organization', 'row_number'],
                                     columns='column_name', 
                                     values='response_value',
                                     aggfunc=lambda x: ' '.join(x)).reset_index()
corps_cc_df_2_3a

column_name,account_number,organization,row_number,C2.3a_C10Potential financial impact,C2.3a_C11Explanation of financial impact,C2.3a_C12Management method,C2.3a_C13Cost of management,C2.3a_C14Comment,C2.3a_C1Identifier,C2.3a_C2Where in the value chain does the risk driver occur?,C2.3a_C3Risk type,C2.3a_C4Primary climate-related risk driver,C2.3a_C5Type of financial impact driver,C2.3a_C6Company- specific description,C2.3a_C7Time horizon,C2.3a_C8Likelihood,C2.3a_C9Magnitude of impact
0,58,ABM INDUSTRIES INC,1,NaN,NaN,NaN,NaN,NaN,Risk 1,Direct operations,Physical risk,Acute: Increased severity of extreme weather e...,Reduced revenue and higher costs from negative...,While some weather events create opportunity f...,Current,About as likely as not,Medium-low
1,58,ABM INDUSTRIES INC,2,NaN,NaN,NaN,NaN,NaN,Risk 2,Customer,Physical risk,Acute: Increased severity of extreme weather e...,Reduced revenues from lower sales/output,While some weather events create opportunity f...,Current,About as likely as not,Medium-low
2,119,Resolute Forest Products Inc.,1,5000000.0,Since this cap and trade system came into forc...,Involvement in industry associations and lobby...,1250000.0,Costs of memberships dues for Canadian and Que...,Risk 1,Direct operations,Transition risk,Policy and legal: Increased pricing of GHG emi...,Policy and legal: Increased operating costs (e...,The Cap and Trade system in Quebec. Since the ...,Current,Virtually certain,Medium
3,119,Resolute Forest Products Inc.,2,4000000.0,Our operational costs have increased at all ou...,"Involvement in industry associations, Governme...",1250000.0,Costs of memberships dues for Canadian and Ont...,Risk 2,Direct operations,Transition risk,Policy and legal: Increased pricing of GHG emi...,Policy and legal: Increased operating costs (e...,A Cap and Trade system was implemented in Onta...,Current,Virtually certain,Low
4,119,Resolute Forest Products Inc.,3,45000000.0,One method for estimating the potential financ...,One of Resolute's greatest opportunities to us...,NaN,"In Quebec, la SOPFEU, an organization responsi...",Risk 3,Supply chain,Physical risk,Chronic: Changes in precipitation patterns and...,"Increased operating costs (e.g., inadequate wa...",Forest fires - Lack of rain for long periods m...,Long-term,More likely than not,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986,831934,"Fourstar Connections, Inc.",5,NaN,Major winter storms represent potential risk f...,Fourstar holds extensive insurance policies fo...,0.0,Cost of insurance policy and execution of reco...,Risk 5,Direct operations,Physical risk,Chronic: Changes in precipitation patterns and...,Reduced revenue from decreased production capa...,"Precipitation extremes, particularly in winter...",Current,About as likely as not,Unknown
1987,831934,"Fourstar Connections, Inc.",6,NaN,Lost revenue due to delays in material sourcing.,Fourstar is engaging its key suppliers regardi...,60000.0,Costs for the management of suppliers and the ...,Risk 6,Supply chain,Physical risk,Chronic: Changes in precipitation patterns and...,Reduced revenue from decreased production capa...,"As is typical in our industry, and dictated by...",Short-term,About as likely as not,Unknown
1988,831987,Microsemi Corporation,1,0.0,Potential financial impact is unknown.,Microsemi has internal policies and programs i...,0.0,Ensuring regulatory compliance is a core part ...,Risk 1,Supply chain,Transition risk,Policy and legal: Mandates on and regulation o...,Policy and legal: Increased operating costs (e...,"Microsemi is subject to various federal, state...",Current,Unlikely,Medium-low
1989,831987,Microsemi Corporation,2,3500000.0,"In 2012, severe flooding in certain regions of...",Microsemi has business continuity processes in...,0.0,Business continuity is a core part of Microsem...,Risk 2,Direct operations,Physical risk,Acute: Increased severity of extreme weather e...,Reduced revenue from decreased production capa...,"Microsemi's facilities and suppliers, along wi...",Short-term,More likely than not,Medium-low
1990,832061,BGIS,1,10000000.0,Currently BGIS has 3 major contracts and pendi...,"Continuous monitoring of costs, schedules and ...",10000.0,NaN,NaN,Customer,Transition risk,Technology: Substitution of existing products ...,Technology: Costs to adopt/deploy new practice...,BGIS is directly responsible for our Clients F...,Medium-term,More likely than not,Medium-high

In [42]:
#(C2.4) Have you identified any climate-related opportunities with the potential to have a substantive financial or strategic impact on your business?

corps_cc_df_2_4a = corps_cc_df[corps_cc_df['question_number'] == 'C2.4a']
corps_cc_df_2_4a = corps_cc_df_2_4a[corps_cc_df_2_4a['response_value'].notnull()]

corps_cc_df_2_4a = corps_cc_df_2_4a.pivot_table(index=['account_number', 'organization', 'row_number'],
                                     columns='column_name', 
                                     values='response_value',
                                     aggfunc=lambda x: ' '.join(x)).reset_index()
corps_cc_df_2_4a

column_name,account_number,organization,row_number,C2.4a_C10Potential financial impact,C2.4a_C11Explanation of financial impact,C2.4a_C12Strategy to realize opportunity,C2.4a_C13Cost to realize opportunity,C2.4a_C14Comment,C2.4a_C1Identifier,C2.4a_C2Where in the value chain does the opportunity occur?,C2.4a_C3Opportunity type,C2.4a_C4Primary climate-related opportunity driver,C2.4a_C5Type of financial impact driver,C2.4a_C6Company- specific description,C2.4a_C7Time horizon,C2.4a_C8Likelihood,C2.4a_C9Magnitude of impact
0,119,Resolute Forest Products Inc.,1,0.0,Due to $13 million invested in energy efficien...,Continuous tracking and forecasting of our mil...,13000000.0,Resolute has invested $13 million in energy ef...,Opp1,Direct operations,Energy source,Participation in carbon market,"Other, please specify: Carbon credits","In 2017, cap and trade systems are in force in...",Short-term,Likely,Medium-low
1,119,Resolute Forest Products Inc.,2,2500000000.0,Resolute further expanded its eco-efficient me...,Resolute further expanded its eco-efficient me...,350000000.0,"In 2015, as part of our business strategy to i...",Opp2,Customer,Products and services,Development and/or expansion of low emission g...,Better competitive position to reflect shiftin...,Increased demand for eco-efficient products. I...,Current,Very likely,Medium
2,119,Resolute Forest Products Inc.,3,30000000.0,"Over the past decade, Resolute has significant...",The construction of a $10 million wood pellet ...,13500000.0,NaN,Opp3,Direct operations,Resilience,Participation in renewable energy programs and...,Increased revenue through new products and ser...,Renewable energy regulations (i.e. Ontario's c...,Short-term,More likely than not,Medium-low
3,119,Resolute Forest Products Inc.,4,15000000000.0,Although it is difficult to quantify both the ...,Tracking and continuous monitoring of shared p...,1250000.0,"Cost of membership in industry associations, s...",Opp4,Customer,Products and services,Shift in consumer preferences,Better competitive position to reflect shiftin...,Building a strong reputation as a leading sust...,Medium-term,Likely,Medium
4,285,3M Company,1,0.0,3M considers the potential financial impact fr...,Our greatest opportunity to overcome global ch...,0.0,3M considers the cost to realize opportunities...,Opp1,Customer,Products and services,Development of new products or services throug...,Increased revenue through new solutions to ada...,3M continues to serve our customers through a ...,Medium-term,Likely,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,831934,"Fourstar Connections, Inc.",3,20000.0,"Change-over to higher efficiency equipment, re...","Change-over to higher efficiency equipment, ap...",40000.0,Cost of equipment and installation.,Opp3,Direct operations,Energy source,Use of lower-emission sources of energy,Returns on investment in low-emission technology,Past investment in energy efficient technology...,Current,Very likely,Medium-low
1548,831934,"Fourstar Connections, Inc.",4,20000.0,Prevention of loss production days due to mate...,Collaborating with existing supply base on con...,70000.0,"Consultancy fees, cost of management / deploym...",Opp4,Supply Chain,Resilience,Resource substitutes/diversification,Increased reliability of supply chain and abil...,"As is the case with all EMS providers, Foursta...",Short-term,Very likely,Medium-low
1549,831934,"Fourstar Connections, Inc.",5,50000.0,New business from customers in new markets.,Collaborate with customers on sustainable / lo...,0.0,Billable service,Opp5,Customer,Markets,Access to new markets,Increased revenues through access to new and e...,Fourstar's pursuit of low-emission / sustainab...,Medium-term,More likely than not,Medium
1550,831934,"Fourstar Connections, Inc.",6,1000000.0,New business from customers in the existing ma...,"Actively marketing sustainability and CSR, pro...",40000.0,Cost of training and marketing.,Opp6,Customer,Markets,Access to new markets,Increased revenues through access to new and e...,Fourstar's onboarding of sustainability initia...,Medium-term,Likely,High
1551,831934,"Fourstar Connections, Inc.",7,50000.0,Increased business due to efficiency gains - r...,Collaborating with our customers around sustai...,0.0,No cost associated with this opportunity.,Opp7,Customer,Products and services,Development and/or expansion of low emission g...,Increased revenue through demand for lower emi...,Fourstar's accounting for lifecycle emissions/...,Short-term,Likely,Medium

<span style="color:red">Annoyingly for both 2.3a and 2.4a, they only put risks and opportunities as Risk1 and Opp1 for example</span>

### Business Strategy

In [45]:
#(C3.1) Are climate-related issues integrated into your business strategy?

corps_cc_df[(corps_cc_df['question_number'] == 'C3.1')] # no one answered this either...

Empty DataFrame
Columns: [account_number, organization, survey_year, response_received_date, accounting_period_to, ors_response_id, submission_date, page_name, module_name, question_number, question_unique_reference, column_number, column_name, table_columns_unique_reference, row_number, row_name, data_point_name, data_point_id, response_value, comments]
Index: []

### Targets and Performance

In [50]:
#(C4.1) Did you have an emissions target that was active in the reporting year?

corps_cc_df[(corps_cc_df['question_number'] == 'C4.1')][['organization','response_value']].groupby('response_value').count().sort_values('organization',ascending=False)

                                     organization
response_value
Absolute target                               220
Intensity target                              178
No target                                     167
Both absolute and intensity targets            83

<span style="color:red">Absolute target is like % reduction from past year, intensity target is like per unit of revenue</span>

In [53]:
#(C4.1a) Provide details of your absolute emissions target(s) and progress made against those targets.

corps_cc_df_4_1a = corps_cc_df[corps_cc_df['question_number'] == 'C4.1a']
corps_cc_df_4_1a = corps_cc_df_4_1a[corps_cc_df_4_1a['response_value'].notnull()]

corps_cc_df_4_1a = corps_cc_df_4_1a.pivot_table(index=['account_number', 'organization', 'row_number'],
                                     columns='column_name', 
                                     values='response_value',
                                     aggfunc=lambda x: ' '.join(x)).reset_index()
corps_cc_df_4_1a

column_name,account_number,organization,row_number,C4.1a_C10% achieved (emissions),C4.1a_C11Target status,C4.1a_C12Please explain,C4.1a_C1Target reference number,C4.1a_C2Scope,C4.1a_C3% emissions in Scope,C4.1a_C4% reduction from base year,C4.1a_C5Base year,C4.1a_C6Start year,C4.1a_C7Base year emissions covered by target (metric tons CO2e),C4.1a_C8Target year,C4.1a_C9Is this a science-based target?
0,119,Resolute Forest Products Inc.,1,100.0,Expired,"Resolute has surpassed, ahead of schedule, the...",Abs 1,Scope 1+2 (location-based),100.0,65.0,2000.0,2012.0,11856979.0,2015.0,"No, and we do not anticipate setting one in th..."
1,285,3M Company,1,20.0,Underway,"3M, as a science-based company, supports the p...",Abs 1,Scope 1+2 (location-based),100.0,50.0,2002.0,2015.0,18300000.0,2025.0,"No, but we anticipate setting one in the next ..."
2,304,The AES Corporation,1,100.0,New,"In Brazil, the scope 2 emissions estimation de...",Abs 1,Scope 2 (location-based),0.17,12.0,2016.0,2017.0,688.08,2017.0,"No, but we anticipate setting one in the next ..."
3,333,"Adobe, Inc.",1,0.0,Underway,Adobe commits to reduce absolute global scope ...,Abs 1,Scope 1 +2 (market-based),100.0,25.0,2015.0,2016.0,64736.0,2025.0,"Yes, this target has been approved as science-..."
4,333,"Adobe, Inc.",2,0.0,Underway,"As with Abs 1, Adobe commits to reduce absolut...",Abs 2,Scope 1 +2 (market-based),100.0,55.0,2015.0,2016.0,64736.0,2040.0,"Yes, this target has been approved as science-..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,831379,Port of Tacoma,2,0.0,Underway,This target was set to align the Port of Tacom...,Abs 2,Scope 1 +2 (market-based),100.0,100.0,2005.0,2017.0,2769.0,2050.0,"Yes, we consider this a science-based target, ..."
491,831379,Port of Tacoma,3,34.0,Underway,This target was set to align the Port of Tacom...,Abs 3,"Other, please specify: All Scope 3 emissions",89.0,80.0,2005.0,2017.0,40058.0,2050.0,"Yes, we consider this a science-based target, ..."
492,831380,Northwest Seaport Alliance,1,20.0,Underway,This target was set to align the NWSA's climat...,Abs 1,"Other, please specify: All Scope 3 Emissions",100.0,50.0,2005.0,2017.0,741920.0,2030.0,"Yes, we consider this a science-based target, ..."
493,831380,Northwest Seaport Alliance,2,20.0,Underway,This target was set to align the NWSA's climat...,Abs 2,"Other, please specify: All Scope 3 Emissions",100.0,80.0,2005.0,2017.0,741920.0,2050.0,"Yes, we consider this a science-based target, ..."
494,831825,Varex Imaging Corporation,1,NaN,Underway,Data was collected and a baseline was establis...,Abs 1,Scope 1 +2 (market-based),100.0,5.0,2017.0,2017.0,49548.0,2018.0,"No, but we anticipate setting one in the next ..."

<span style="color:red">Interesting to see their % emission reductions compared to last year</span>

In [54]:
#(C4.1b) Provide details of your emissions intensity target(s) and progress made against those target(s).

corps_cc_df_4_1b = corps_cc_df[corps_cc_df['question_number'] == 'C4.1b']
corps_cc_df_4_1b = corps_cc_df_4_1b[corps_cc_df_4_1b['response_value'].notnull()]

corps_cc_df_4_1b = corps_cc_df_4_1b.pivot_table(index=['account_number', 'organization', 'row_number'],
                                     columns='column_name', 
                                     values='response_value',
                                     aggfunc=lambda x: ' '.join(x)).reset_index()
corps_cc_df_4_1b

column_name,account_number,organization,row_number,C4.1b_C10Is this a science-based target?,C4.1b_C11% achieved (emissions),C4.1b_C12Target status,C4.1b_C13Please explain,C4.1b_C14% change anticipated in absolute Scope 1+2 emissions,C4.1b_C15% change anticipated in absolute Scope 3 emissions,C4.1b_C1Target reference number,C4.1b_C2Scope,C4.1b_C3% emissions in Scope,C4.1b_C4% reduction from baseline year,C4.1b_C5Metric,C4.1b_C6Base year,C4.1b_C7Start year,C4.1b_C8Normalized baseline year emissions covered by target (metric tons CO2e),C4.1b_C9Target year
0,58,ABM INDUSTRIES INC,1,"No, and we do not anticipate setting one in th...",100.0,Underway,ABM has committed to reducing our metric tons ...,19.78,0.0,Int 1,Scope 1+2 (location-based),100.0,15.0,Metric tons CO2e per unit hour worked,2011.0,2011.0,58120.0,2020.0
1,64,Abbott Laboratories,1,"No, and we do not anticipate setting one in th...",86.8,Underway,All environmental data have been adjusted to a...,9.6,0.0,Int 1,Scope 1+2 (location-based),100.0,40.0,Metric tons CO2e per unit revenue,2010.0,2012.0,5.68e-05,2020.0
2,285,3M Company,1,"No, but we anticipate setting one in the next ...",6.7,Underway,Energy efficiency improvements help address ri...,0.0,0.0,Int 1,Scope 1+2 (location-based),100.0,15.0,Metric tons CO2e per unit revenue,2015.0,2015.0,186.0,2025.0
3,304,The AES Corporation,1,"No, and we do not anticipate setting one in th...",2.0,Underway,The target is for AES business in Chile. The ...,25.0,0.0,Int 1,Scope 1,15.39,25.0,Metric tons CO2e per megawatt hour (MWh)*,2016.0,2017.0,12599494.0,2021.0
4,333,"Adobe, Inc.",1,"Yes, this target has been approved as science-...",100.0,Underway,Adobe will strive to reduce scope 3 business t...,0.0,43.0,Int 1,Scope 3: Business travel,100.0,5.0,Metric tons CO2e per unit FTE employee,2015.0,2016.0,2.09,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,70601,Versum,1,"No, and we do not anticipate setting one in th...",60.0,Underway,Versum Materials began its first full calendar...,40.0,0.0,Int 1,Scope 1 +2 (market-based),100.0,0.0,Metric tons CO2e per metric ton of product,2015.0,2015.0,1.0,2017.0
350,829863,"SERIGRAPH, INC.",1,"No, and we do not anticipate setting one in th...",100.0,Underway,Achieving target,NaN,NaN,Int 1,Scope 1,9.0,38.0,Metric tons CO2e per unit hour worked,2008.0,2008.0,0.162,2017.0
351,831379,Port of Tacoma,1,"No, but we are reporting another target that i...",22.0,Underway,The Northwest Ports Clean Air Strategy (NWPCAS...,0.0,22.0,Int 1,"Other, please specify: Mobile Source Cargo Tra...",38.0,15.0,"Other, please specify: Tons CO2e per ton of ca...",2005.0,2015.0,0.0035,2020.0
352,831380,Northwest Seaport Alliance,1,"No, but we are reporting another target that i...",17.0,Underway,The Northwest Ports Clean Air Strategy (NWPCAS...,0.0,20.0,Int 1,"Other, please specify: Mobile Source Cargo Tra...",100.0,15.0,"Other, please specify: Tons CO2e per ton of ca...",2005.0,2015.0,0.0276,2020.0
353,832061,BGIS,1,"No, but we are reporting another target that i...",7.4,Underway,BGIS is committed to reducing the GHG emission...,15.0,-15.0,Int 1,Scope 1+2 (location-based),100.0,20.0,Metric tons CO2e per unit FTE employee,2016.0,2017.0,7209.9,2020.0

<span style="color:red">Interesting to see the metrics companies used for their intensive emission targets...</span>

In [86]:
#(C4.2) Provide details of other key climate-related targets not already reported in question C4.1/a/b.

corps_cc_df_4_2 = corps_cc_df[corps_cc_df['question_number'] == 'C4.2']
corps_cc_df_4_2 = corps_cc_df_4_2[corps_cc_df_4_2['response_value'].notnull()]

corps_cc_df_4_2 = corps_cc_df_4_2.pivot_table(index=['account_number', 'organization', 'row_number'],
                                     columns='column_name', 
                                     values='response_value',
                                     aggfunc=lambda x: ' '.join(x)).reset_index()
corps_cc_df_4_2.head()
#pd.options.display.max_colwidth = 600
#corps_cc_df_4_2[(corps_cc_df_4_2['organization'] == "Macy's, Inc.") & (corps_cc_df_4_2['row_number'] == 2)][['C4.2_C11Please explain']]

column_name,account_number,organization,row_number,C4.2_C10Target Status,C4.2_C11Please explain,C4.2_C12Part of emissions target,C4.2_C13Is this target part of an overarching initiative?,C4.2_C1Target,C4.2_C2KPI â€“ Metric numerator,C4.2_C3KPI â€“ Metric denominator (intensity targets only),C4.2_C4Base year,C4.2_C5Start year,C4.2_C6Target year,C4.2_C7KPI in baseline year,C4.2_C8KPI in target year,C4.2_C9% achieved in reporting year
0,119,Resolute Forest Products Inc.,1,Replaced,"Optimizing the use of renewable energy sources such as hydroelectricity and carbon-neutral biomass, while reducing consumption of fossil fuels, is a key element of our strategy to improve our carbon footprint. Replacing high-emission fuels like coal with less-carbon-intensive fuels benefits both the environment and our bottom line. In 2014, for example, we replaced the remaining coal used at our operations with natural gas, a less-carbon-intensive fuel, in order to become scope 1 coal-free as of April 2014. We also reduced bunker C oil use at our Clermont and Saint-FÃ©licien mills in Quebec.","In 2017, Resolute generated 74% of its total energy needs (25,840 GWh) from renewable sources (hydroelectricity and biomass), up from 71% in 2013, and 72% in 2014.In 2017, 82% of our fuel energy usage (19,799 GWh) was derived from biomass.1 By utilizing bark, wood residues and biosolids for energy instead of sending these waste products to landfills, Resolute is able to reduce consumption of fossil fuels, as well as the GHG emissions associated with their use.",NaN,Renewable energy consumption,Renewable energy as a % of total energy (GWh),Total energy (GWh),2014.0,2015.0,2017.0,14428.0,10756.0,74.0
1,285,3M Company,1,Underway,"3M has a sustainability goal to Increase renewable energy to 25% of total electricity use.3M's total wind energy purchases have reached 579 gigawatt hours of wind energy or 17.9 percent of our company's total global electricity use for 2017.The ""% achieved in reporting year"" was calculated as 17.9% / 25%=71.6%",NaN,"No, it's not part of an overarching initiative",Renewable energy consumption,Renewable Electricity,Total Electricity used,2015.0,2015.0,2025.0,0.0,25.0,71.6
2,304,The AES Corporation,1,Underway,"In 2017, AES announced that will improve the carbon intensity of all its portfolio by 25% from 2016 to 2020. The company will achieve the target trough a combination of emission reduction activities (efficiencies, retirements, conversions) as well a portfolio management (divest highly carbon intensive business). The Company has already taken steps that are expected to reduce its carbon intensity by 25%, or 20 million tons of carbon dioxide emissions, from 2016 to 2020, including:The sale or retirement of 4.3 GW of merchant coal-fired generation, representing 37% of the Company's coal-fired...",NaN,"No, it's not part of an overarching initiative","Other, please specify: Improve carbon intensity of portfolio",tons of CO2 emissions,"megawatts hours ""MWh""",2016.0,2017.0,2020.0,0.671,0.52,6.84
3,333,"Adobe, Inc.",1,Underway,"Adobe Renewable Energy (RE100) goal: 100% of Adobe operations and digital delivery of product to be powered with renewable energy by 2035 (includes owned and managed sites, owned data centers, and managed collocated data centers (CoLos)) as well as ''Fuel Switchingâ€ out all fossil fuel use -- diesel, natural gas, and electricity -- including all electricity presently produced from our fuel cells. It is important to note that Adobe reached ""carbon neutrality"" in 2015, a goal set in 2012 (prior to our Cloud strategy implementation) through purchase of clean, local carbon offsets and unbund...",100% of all energy consumed in 2035 will be from renewable sources.,RE100,Renewable energy consumption,All energy consumed,NaN,2015.0,2016.0,2035.0,192545.0,100.0,1.0
4,333,"Adobe, Inc.",2,Underway,"Adobe's renewable energy production goal for this target is for on-site renewable energy production in total. In 2010 Adobe installed Windspire wind turbines at Adobe's San Jose headquarters with the initial goal of producing up to 10% of the San Jose sites energy by the wind. Unfortunately, we have never achieved that level of production but we plan to continue to review and report on it as well as determine if the Windspires are having a positive impact on energy use, our communities perception of Adobe with this iconic symbol in San Jose, and employee and community affinity for compan...","Medium- and long term Science-Based Targets, RE100 goals, internal innovation objectives.",RE100,Renewable energy production,MWh,per year,2010.0,2010.0,2035.0,26954.0,16080.0,1.0

In [96]:
corps_cc_df[(corps_cc_df['question_number'] == 'C4.2') & (corps_cc_df['column_number'] == 1.0)][['organization','response_value']].groupby('response_value').count().sort_values('organization',ascending=False).head(10)

                              organization
response_value
Renewable energy consumption           109
Waste                                   92
Energy usage                            86
Energy productivity                     26
Engagement with suppliers               20
Renewable energy production             16
Methane reduction target                14
Zero/low-carbon vehicle                 10
Other, please specify: Water             9
Land use                                 4